export const  data = {
    "1": {
      "id": 1,
      "upcoming_launch_image": "image-1",
      "upcoming_launch_title": "Falcon 9 - Starlink 28",
      "upcoming_launch_date": "2024-10-15",
      "upcoming_launch_time": "09:30:00",
      "upcoming_launch_base": "Cape Canaveral",
      "upcoming_launch_location": "Florida",
      "upcoming_launch_rocket": "Falcon 9",
      "upcoming_launch_description": "Deployment of the 28th batch of Starlink satellites.",
      "upcoming_launch_company": "SpaceX",
      "url": "http://spacex.com/starlink28"
    },
    "2": {
      "id": 2,
      "upcoming_launch_image": "image-2",
      "upcoming_launch_title": "Ariane 5 - VA257",
      "upcoming_launch_date": "2024-11-02",
      "upcoming_launch_time": "19:00:00",
      "upcoming_launch_base": "Guiana Space Centre",
      "upcoming_launch_location": "French Guiana",
      "upcoming_launch_rocket": "Ariane 5",
      "upcoming_launch_description": "Launch of two communications satellites.",
      "upcoming_launch_company": "Arianespace",
      "url": "http://arianespace.com/va257"
    },
    "3": {
      "id": 3,
      "upcoming_launch_image": "image-3",
      "upcoming_launch_title": "Atlas V - NROL-101",
      "upcoming_launch_date": "2024-12-05",
      "upcoming_launch_time": "18:45:00",
      "upcoming_launch_base": "Vandenberg SFB",
      "upcoming_launch_location": "California",
      "upcoming_launch_rocket": "Atlas V 401",
      "upcoming_launch_description": "Classified payload for the National Reconnaissance Office.",
      "upcoming_launch_company": "ULA",
      "url": "http://ula.com/nrol-101"
    },
    "4": {
      "id": 4,
      "upcoming_launch_image": "image-4",
      "upcoming_launch_title": "Long March 5B - Tianhe Module",
      "upcoming_launch_date": "2024-10-28",
      "upcoming_launch_time": "13:00:00",
      "upcoming_launch_base": "Wenchang",
      "upcoming_launch_location": "China",
      "upcoming_launch_rocket": "Long March 5B",
      "upcoming_launch_description": "Launch of the Tianhe core module for China's space station.",
      "upcoming_launch_company": "CNSA",
      "url": "http://cnsa.gov/tianhe"
    },
    "5": {
      "id": 5,
      "upcoming_launch_image": "image-5",
      "upcoming_launch_title": "Soyuz-2.1a - Progress MS-19",
      "upcoming_launch_date": "2024-11-18",
      "upcoming_launch_time": "08:30:00",
      "upcoming_launch_base": "Baikonur Cosmodrome",
      "upcoming_launch_location": "Kazakhstan",
      "upcoming_launch_rocket": "Soyuz-2.1a",
      "upcoming_launch_description": "Resupply mission to the International Space Station.",
      "upcoming_launch_company": "Roscosmos",
      "url": "http://roscosmos.ru/progress-ms19"
    },
    "6": {
      "id": 6,
      "upcoming_launch_image": "image-6",
      "upcoming_launch_title": "Falcon 9 - Crew-8 Mission",
      "upcoming_launch_date": "2024-12-10",
      "upcoming_launch_time": "12:00:00",
      "upcoming_launch_base": "Kennedy Space Center",
      "upcoming_launch_location": "Florida",
      "upcoming_launch_rocket": "Falcon 9",
      "upcoming_launch_description": "Crewed mission to the ISS as part of NASA's Commercial Crew Program.",
      "upcoming_launch_company": "SpaceX",
      "url": "http://spacex.com/crew-8"
    },
    "7": {
      "id": 7,
      "upcoming_launch_image": "image-7",
      "upcoming_launch_title": "Electron - BlackSky Global",
      "upcoming_launch_date": "2024-10-24",
      "upcoming_launch_time": "05:45:00",
      "upcoming_launch_base": "Rocket Lab Launch Complex 1",
      "upcoming_launch_location": "New Zealand",
      "upcoming_launch_rocket": "Electron",
      "upcoming_launch_description": "Launch of two Earth observation satellites for BlackSky Global.",
      "upcoming_launch_company": "Rocket Lab",
      "url": "http://rocketlabusa.com/blacksky"
    },
    "8": {
      "id": 8,
      "upcoming_launch_image": "image-8",
      "upcoming_launch_title": "Antares - NG-18",
      "upcoming_launch_date": "2024-11-05",
      "upcoming_launch_time": "13:15:00",
      "upcoming_launch_base": "Wallops Flight Facility",
      "upcoming_launch_location": "Virginia",
      "upcoming_launch_rocket": "Antares 230+",
      "upcoming_launch_description": "Resupply mission to the International Space Station.",
      "upcoming_launch_company": "Northrop Grumman",
      "url": "http://northropgrumman.com/ng18"
    },
    "9": {
      "id": 9,
      "upcoming_launch_image": "image-9",
      "upcoming_launch_title": "Falcon Heavy - USSF-52",
      "upcoming_launch_date": "2024-12-21",
      "upcoming_launch_time": "16:30:00",
      "upcoming_launch_base": "Cape Canaveral",
      "upcoming_launch_location": "Florida",
      "upcoming_launch_rocket": "Falcon Heavy",
      "upcoming_launch_description": "Classified military mission for the U.S. Space Force.",
      "upcoming_launch_company": "SpaceX",
      "url": "http://spacex.com/ussf52"
    },
    "10": {
      "id": 10,
      "upcoming_launch_image": "image-10",
      "upcoming_launch_title": "Vega C - LARES 2",
      "upcoming_launch_date": "2024-11-25",
      "upcoming_launch_time": "23:45:00",
      "upcoming_launch_base": "Guiana Space Centre",
      "upcoming_launch_location": "French Guiana",
      "upcoming_launch_rocket": "Vega C",
      "upcoming_launch_description": "Deployment of LARES 2, an Italian geodetic satellite.",
      "upcoming_launch_company": "Arianespace",
      "url": "http://arianespace.com/lares2"
    },
    "11": {
      "id": 11,
      "upcoming_launch_image": "image-11",
      "upcoming_launch_title": "Falcon 9 - GPS III SV05",
      "upcoming_launch_date": "2024-12-30",
      "upcoming_launch_time": "14:00:00",
      "upcoming_launch_base": "Cape Canaveral",
      "upcoming_launch_location": "Florida",
      "upcoming_launch_rocket": "Falcon 9",
      "upcoming_launch_description": "Launch of the GPS III SV05 satellite for the U.S. Space Force.",
      "upcoming_launch_company": "SpaceX",
      "url": "http://spacex.com/gps3-sv05"
    },
    "12": {
      "id": 12,
      "upcoming_launch_image": "image-12",
      "upcoming_launch_title": "Soyuz-2.1b - OneWeb 19",
      "upcoming_launch_date": "2024-11-17",
      "upcoming_launch_time": "07:00:00",
      "upcoming_launch_base": "Vostochny Cosmodrome",
      "upcoming_launch_location": "Russia",
      "upcoming_launch_rocket": "Soyuz-2.1b",
      "upcoming_launch_description": "Deployment of OneWeb satellites for global internet coverage.",
      "upcoming_launch_company": "OneWeb",
      "url": "http://oneweb.world/launch19"
    },
    "13": {
      "id": 13,
      "upcoming_launch_image": "image-13",
      "upcoming_launch_title": "GSLV Mk III - Gaganyaan Demo Mission",
      "upcoming_launch_date": "2024-10-05",
      "upcoming_launch_time": "10:30:00",
      "upcoming_launch_base": "Satish Dhawan Space Centre",
      "upcoming_launch_location": "India",
      "upcoming_launch_rocket": "GSLV Mk III",
      "upcoming_launch_description": "Uncrewed test flight for India's human spaceflight program.",
      "upcoming_launch_company": "ISRO",
      "url": "http://isro.gov/gaganyaan"
    },
    "14": {
      "id": 14,
      "upcoming_launch_image": "image-14",
      "upcoming_launch_title": "Falcon 9 - DART Mission",
      "upcoming_launch_date": "2024-10-29",
      "upcoming_launch_time": "21:15:00",
      "upcoming_launch_base": "Vandenberg SFB",
      "upcoming_launch_location": "California",
      "upcoming_launch_rocket": "Falcon 9",
      "upcoming_launch_description": "NASA's DART mission to test asteroid deflection technology.",
      "upcoming_launch_company": "SpaceX",
      "url": "http://nasa.gov/dart"
    },
    "15": {
      "id": 15,
      "upcoming_launch_image": "image-15",
      "upcoming_launch_title": "Soyuz-2.1b - Meteor M2-3",
      "upcoming_launch_date": "2024-12-12",
      "upcoming_launch_time": "09:45:00",
      "upcoming_launch_base": "Baikonur Cosmodrome",
      "upcoming_launch_location": "Kazakhstan",
      "upcoming_launch_rocket": "Soyuz-2.1b",
      "upcoming_launch_description": "Launch of a Russian meteorological satellite.",
      "upcoming_launch_company": "Roscosmos",
      "url": "http://roscosmos.ru/meteor-m2-3"
    },
    "16": {
      "id": 16,
      "upcoming_launch_image": "image-16",
      "upcoming_launch_title": "H-IIA - Inmarsat GX10A",
      "upcoming_launch_date": "2024-10-13",
      "upcoming_launch_time": "11:30:00",
      "upcoming_launch_base": "Tanegashima Space Center",
      "upcoming_launch_location": "Japan",
      "upcoming_launch_rocket": "H-IIA",
      "upcoming_launch_description": "Launch of the GX10A communications satellite for Inmarsat.",
      "upcoming_launch_company": "MHI",
      "url": "http://mhi.com/h2a-gx10a"
    },
    "17": {
      "id": 17,
      "upcoming_launch_image": "image-17",
      "upcoming_launch_title": "Soyuz-2.1v - Kosmos 2559",
      "upcoming_launch_date": "2024-11-03",
      "upcoming_launch_time": "05:30:00",
      "upcoming_launch_base": "Plesetsk Cosmodrome",
      "upcoming_launch_location": "Russia",
      "upcoming_launch_rocket": "Soyuz-2.1v",
      "upcoming_launch_description": "Launch of a military satellite for Russia's Ministry of Defence.",
      "upcoming_launch_company": "Roscosmos",
      "url": "http://roscosmos.ru/kosmos2559"
    },
    "18": {
      "id": 18,
      "upcoming_launch_image": "image-18",
      "upcoming_launch_title": "Ariane 5 - VA259",
      "upcoming_launch_date": "2024-12-20",
      "upcoming_launch_time": "20:15:00",
      "upcoming_launch_base": "Guiana Space Centre",
      "upcoming_launch_location": "French Guiana",
      "upcoming_launch_rocket": "Ariane 5",
      "upcoming_launch_description": "Dual-payload launch of communications satellites.",
      "upcoming_launch_company": "Arianespace",
      "url": "http://arianespace.com/va259"
    },
    "19": {
      "id": 19,
      "upcoming_launch_image": "image-19",
      "upcoming_launch_title": "Electron - Capella 9",
      "upcoming_launch_date": "2024-12-07",
      "upcoming_launch_time": "04:45:00",
      "upcoming_launch_base": "Rocket Lab Launch Complex 1",
      "upcoming_launch_location": "New Zealand",
      "upcoming_launch_rocket": "Electron",
      "upcoming_launch_description": "Launch of a radar imaging satellite for Capella Space.",
      "upcoming_launch_company": "Rocket Lab",
      "url": "http://rocketlabusa.com/capella9"
    },
    "20": {
      "id": 20,
      "upcoming_launch_image": "image-20",
      "upcoming_launch_title": "Falcon Heavy - Europa Clipper",
      "upcoming_launch_date": "2024-11-27",
      "upcoming_launch_time": "13:00:00",
      "upcoming_launch_base": "Kennedy Space Center",
      "upcoming_launch_location": "Florida",
      "upcoming_launch_rocket": "Falcon Heavy",
      "upcoming_launch_description": "NASA's Europa Clipper mission to explore Jupiter's moon Europa.",
      "upcoming_launch_company": "SpaceX",
      "url": "http://nasa.gov/europa-clipper"
    },
    "21": {
      "id": 21,
      "upcoming_launch_image": "image-21",
      "upcoming_launch_title": "Soyuz-2.1b - Luch Relay Satellite",
      "upcoming_launch_date": "2024-12-09",
      "upcoming_launch_time": "06:30:00",
      "upcoming_launch_base": "Baikonur Cosmodrome",
      "upcoming_launch_location": "Kazakhstan",
      "upcoming_launch_rocket": "Soyuz-2.1b",
      "upcoming_launch_description": "Launch of a Russian Luch relay communications satellite.",
      "upcoming_launch_company": "Roscosmos",
      "url": "http://roscosmos.ru/luch-relay"
    },
    "22": {
      "id": 22,
      "upcoming_launch_image": "image-22",
      "upcoming_launch_title": "Soyuz-2.1a - Progress MS-22",
      "upcoming_launch_date": "2024-12-28",
      "upcoming_launch_time": "07:15:00",
      "upcoming_launch_base": "Baikonur Cosmodrome",
      "upcoming_launch_location": "Kazakhstan",
      "upcoming_launch_rocket": "Soyuz-2.1a",
      "upcoming_launch_description": "Cargo resupply mission to the ISS.",
      "upcoming_launch_company": "Roscosmos",
      "url": "http://roscosmos.ru/progress-ms22"
    },
    "23": {
      "id": 23,
      "upcoming_launch_image": "image-23",
      "upcoming_launch_title": "H-IIA - DSN-2",
      "upcoming_launch_date": "2024-12-17",
      "upcoming_launch_time": "09:00:00",
      "upcoming_launch_base": "Tanegashima Space Center",
      "upcoming_launch_location": "Japan",
      "upcoming_launch_rocket": "H-IIA",
      "upcoming_launch_description": "Launch of DSN-2, a communication satellite for Japan's Ministry of Defense.",
      "upcoming_launch_company": "MHI",
      "url": "http://mhi.com/dsn-2"
    },
    "24": {
      "id": 24,
      "upcoming_launch_image": "image-24",
      "upcoming_launch_title": "Falcon 9 - Sentinel-6 Michael Freilich",
      "upcoming_launch_date": "2024-12-15",
      "upcoming_launch_time": "13:45:00",
      "upcoming_launch_base": "Vandenberg SFB",
      "upcoming_launch_location": "California",
      "upcoming_launch_rocket": "Falcon 9",
      "upcoming_launch_description": "NASA's mission to monitor global sea levels.",
      "upcoming_launch_company": "NASA",
      "url": "http://nasa.gov/sentinel6"
    },
    "25": {
      "id": 25,
      "upcoming_launch_image": "image-25",
      "upcoming_launch_title": "Soyuz-2.1b - Glonass-K2",
      "upcoming_launch_date": "2024-12-22",
      "upcoming_launch_time": "14:30:00",
      "upcoming_launch_base": "Plesetsk Cosmodrome",
      "upcoming_launch_location": "Russia",
      "upcoming_launch_rocket": "Soyuz-2.1b",
      "upcoming_launch_description": "Launch of a navigation satellite for Russia's GLONASS system.",
      "upcoming_launch_company": "Roscosmos",
      "url": "http://roscosmos.ru/glonass-k2"
  }
}
